parameters:
    ars_thanea_kunstmaan_extra.twig.render_page_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\RenderPageTwigExtension'
    ars_thanea_kunstmaan_extra.twig.node_versions_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\NodeVersionsTwigExtension'
    ars_thanea_kunstmaan_extra.twig.content_category_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\ContentCategoryTwigExtension'
    ars_thanea_kunstmaan_extra.twig.site_tree_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\SiteTreeTwigExtension'
    ars_thanea_kunstmaan_extra.twig.page_url_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\PageUrlTwigExtension'
    ars_thanea_kunstmaan_extra.twig.content_type_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\ContentTypeTwigExtension'
    ars_thanea_kunstmaan_extra.twig.bem_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\BemTwigExtension'
    ars_thanea_kunstmaan_extra.twig.form_attributes_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\FormAttributesTwigExtension'
    ars_thanea_kunstmaan_extra.twig.typography_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\TypographyTwigExtension'
    ars_thanea_kunstmaan_extra.twig.pretty_date_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\PrettyDateTwigExtension'
    ars_thanea_kunstmaan_extra.twig.navigation_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\NavigationTwigExtension'
    ars_thanea_kunstmaan_extra.twig.imagine_twig_extension.class: 'ArsThanea\KunstmaanExtraBundle\Twig\ImagineTwigExtension'

services:

    ars_thanea_kunstmaan_extra.twig.render_page_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.render_page_twig_extension.class%'
        arguments: [ '@fragment.handler', '@kunstmaan_extra.ref_id_provider' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.node_versions_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.node_versions_twig_extension.class%'
        arguments: [ '@kunstmaan_extra.public_node_versions', '@kunstmaan_extra.content_type' ]
        tags:
            - { name: twig.extension }


    ars_thanea_kunstmaan_extra.twig.content_category_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.content_category_twig_extension.class%'
        arguments: [ '@kunstmaan_extra.content_category', '@kunstmaan_utilities.slugifier' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.site_tree_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.site_tree_twig_extension.class%'
        arguments: [ '@kunstmaan_extra.content_type', '@kunstmaan_extra.site_tree', '@kunstmaan_admin.domain_configuration' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.page_url_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.page_url_twig_extension.class%'
        arguments: [ '@kunstmaan_extra.page_url', '@router' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.content_type_twig_extension:
        public: false
        class: '%ars_thanea_kunstmaan_extra.twig.content_type_twig_extension.class%'
        arguments: [ '@doctrine.orm.entity_manager', '@kunstmaan_extra.content_type' ]
        tags:
            - { name: twig.extension }


    ars_thanea_kunstmaan_extra.twig.bem_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.bem_twig_extension.class%'
        public: false
        arguments: [ '@kunstmaan_extra.wysiwyg_filter' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.form_attributes_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.form_attributes_twig_extension.class%'
        public: false
        tags:
            - { name: twig.extension }


    ars_thanea_kunstmaan_extra.twig.typography_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.typography_twig_extension.class%'
        public: false
        tags:
            - { name: twig.extension }


    ars_thanea_kunstmaan_extra.twig.pretty_date_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.pretty_date_twig_extension.class%'
        public: false
        arguments: [ '@kunstmaan_extra.intl.date_formatter' ]
        tags:
            - { name: twig.extension }

    ars_thanea_kunstmaan_extra.twig.navigation_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.navigation_twig_extension.class%'
        public: false
        arguments: [ '@kunstmaan_extra.navigation.navigation' ]
        tags:
            - { name: twig.extension }


    ars_thanea_kunstmaan_extra.twig.imagine_twig_extension:
        class: '%ars_thanea_kunstmaan_extra.twig.imagine_twig_extension.class%'
        public: false
        arguments:
          - '@ars_thanea_kunstmaan_extra.imagine.srcset_calculator'
          - '@?ars_thanea.kunstmaan_extra.imagine.imgix_filter'
        tags:
            - { name: twig.extension }
